line-length = 120
target-version = "py39"

[lint]
select = ["F", "E", "W"]
ignore = []

[lint.per-file-ignores]
# Example (uncomment to ignore unused imports in package init):
# "py/ui/__init__.py" = ["F401"]

[format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
